SELECT PERSON_ID, CAST(DRUG_CONCEPT_ID as VARCHAR(4000)) as DRUG_PATH
INTO #USAGE_PATH
FROM #EXPOSURE_SEQUENCE
WHERE ORDINAL = 1;

UPDATE #USAGE_PATH SET DRUG_PATH = CONCAT(DRUG_PATH, '-end')
WHERE PERSON_ID not in (select person_id from #EXPOSURE_SEQUENCE where ORDINAL = 2);
