UPDATE #USAGE_PATH SET DRUG_PATH = CONCAT(DRUG_PATH, CONCAT('-', CAST(#EXPOSURE_SEQUENCE.DRUG_CONCEPT_ID as VARCHAR(50))))
FROM #EXPOSURE_SEQUENCE WHERE #USAGE_PATH.PERSON_ID = #EXPOSURE_SEQUENCE.PERSON_ID AND #EXPOSURE_SEQUENCE.ORDINAL = @sequence;

UPDATE #USAGE_PATH SET DRUG_PATH = CONCAT(DRUG_PATH, '-end')
WHERE PERSON_ID in (
  select e.person_id from #EXPOSURE_SEQUENCE e
  LEFT JOIN #EXPOSURE_SEQUENCE n on e.person_id = n.person_id and n.ordinal = e.ordinal + 1
  where e.ORDINAL = @sequence and n.person_id is null);
